services:
  - type: web
    name: womens-safety-backend
    env: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: womens-safety-db
          property: connectionString
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: FRONTEND_URL
        sync: false

  - type: web
    name: womens-safety-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: womens-safety-backend
          property: host
          envVarKey: RENDER_EXTERNAL_URL

databases:
  - name: womens-safety-db
    databaseName: womens_safety_db
    user: womens_safety_user
    plan: starter
