"""Add ended_at to sos_log

Revision ID: 25205e35ed70
Revises: 307c37324021
Create Date: 2025-08-23 03:42:51.370335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25205e35ed70'
down_revision = '307c37324021'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sos_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ended_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sos_log', schema=None) as batch_op:
        batch_op.drop_column('ended_at')

    # ### end Alembic commands ###
