"""add profile_image and preferences to user

Revision ID: 307c37324021
Revises: a0a0a5b5b04e
Create Date: 2025-08-19 02:32:08.935511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '307c37324021'
down_revision = 'a0a0a5b5b04e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('preferences', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('preferences')
        batch_op.drop_column('profile_image')

    # ### end Alembic commands ###
